### PR TITLE
Try out new model

### PR DESCRIPTION
**Pull request by saulshanabrook**
This addresses #1 and #2 by demonstrating a way to structure this repo, that separates high level/exposed python lowering from low level/lib* lowering.

The aim was to allow users to `@jit` a function and use the same Python API that they are used to for the plures projects. But, we also expose another lower level API, that we use internally (and users could use as well), to implement higher level functions. This mirrors the underlying C header files. The goal here is to keep us sane, by mirroring the existing names and functions in the C libraries.

- [x] Add PyNdtType which is same as NdtType
  - [x] copy boxing/unboxing
- [x] add `CONST_NDT` as casting fn
- [x] add `Ndt_FromType` as casting fn
- [x] ~~Create C function to create ndt_array_t~~
  - [x] ~~expose as python function create_ndt_array_t~~
- [x] ~~Create C function to get shape of ndt_array_t~~
  - [x] ~~expose as python attribute of NdtArrayType~~
- [x] Hardcode in struct sizes
- [x] Create high level `shape` attribute of  `PyNdtType`

### CODE REVIEW

**Comment by pearu** [comment]
When running the tests, only `test_boxes_unboxes` passes. Other tests fail with stopping Python with error message:
```
LLVM ERROR: Program used external function 'ndt_as_ndarray' which could not be resolved!
```

Also, I would like to give a try to replace
```
ndt_t = ir.ArrayType(char, sizes.SIZEOF_NDT_T)
```
with
```
ndt_t = ir.IntType(sizes.SIZEOF_NDT_T)
```
so that `ndt_t` would become single value type for llvm.

**Comment by pearu** [comment]
When trying to compile_isolated, say, `def foo(x): return`, it fails with
```
Type of #3 arg mismatch: [112 x i8]* != i8*
```
Just a bit..

**Comment by saulshanabrook** [comment]
> SOLUTION: ndt_as_ndarray is defined in libndtypes, adding the following code to libndtypes.py fixes the LLVM ERROR:

Good call. I added this but also loading `'libndtypes.dylib'` on mac, so it works for me. I also added CI, so that we can catch these errors more easily.

> so that ndt_t would become single value type for llvm.

Is it that you would think this would generate more performant code? If we switched, I think it would be `ndt_t = ir.IntType(8 * sizes.SIZEOF_NDT_T)` not `ndt_t = ir.IntType(sizes.SIZEOF_NDT_T)`, since [`IntType` takes the number of bits](http://llvmlite.readthedocs.io/en/latest/user-guide/ir/types.html#llvmlite.ir.IntType) and `sizeof` returns the number of `char`s/bytes. 

> Getting struct values from a wide integer requires two binary operations (and_ and ashr, it could be optimized to one when using trunc) between wide integers.

When I think of implementing it this way, I wouldn't ever operate on the integers themselves, just the pointers. So if we have a pointer to an `ndt_t`, we just offset that pointer by the right amount of bytes and then call that a pointer to an `ndt_ndarray_t`.

**Comment by pearu** [comment]
> I think it would be ndt_t = ir.IntType(8 * sizes.SIZEOF_NDT_T)

Yes, that is correct. This also resolved python segfaulting. Thanks!

Do you know how to get a reference of a value using IR? This is needed in order to use IntegerModel and passing the values to ndt_as_ndarray.

Btw, when using PrimitiveModel, ir.ArrayType and ir.IntType are equivalent performance-wise.

**Comment by saulshanabrook** [comment]
OK I fixed ndim to not create the ndarray struct. I also split the files into directories to hopefully make it easier to navigate the code.

**Comment by saulshanabrook** [comment]
> Do you know how to get a reference of a value using IR? This is needed in order to use IntegerModel and passing the values to ndt_as_ndarray.

I don't think this is possible. [src](http://llvm.1065342.n5.nabble.com/is-it-possible-to-get-a-pointer-to-a-value-td58656.html):

> A pointer points to memory. If not stored, a value may live in a  register. So you really need the alloca.

**Pull request merged**
