### PR TITLE
Remove `CONDA_PREFIX` env variable dependency

### PR DESCRIPTION
**Pull request by andersy005**
Fixes https://github.com/Quansight/numba-xnd/issues/14

### CODE REVIEW

**Comment by saulshanabrook** [comment]
I wonder why circle ci didn't run on this...

**Comment by saulshanabrook** [comment]
I'll try this locally. @pearu do you have any comments on this?

**Comment by saulshanabrook** [comment]
Thanks for this.

**Comment by pearu** [comment]
Using `get_python_lib` approach seems to be more robust than using CONDA_PREFIX indeed. It should work also in non-conda environment.

However, this issue illustrates another xnd packing/installation issue: `libxnd.{a,so], libndtypes.{a,so}, libgumath.{a,so}` are installed in two places, in `<prefix>/lib` and in `<prefix>/python<vers>/site-packages/{xnd,ndtypes,gumath}`. While perhaps practical during development, imho, the libraries should be installed only to `<prefix>/lib`, where setup.py can be configured to pick these up.
Reasoning: right now these libraries are used by C and Python projects. Soon we will have Ruby support. It's not efficient to install three identical libraries for each target language. There will be more copies when installing different versions of the same language. IMHO, this is a potential source of confusion.
Perhaps the above should be a separete issue...

**Pull request merged**
